               numerical python

               advantage of numerical python

               allows several mathmatical operations

               faster operation

In [ ]:
import numpy as np


list vs numpy --time taken

In [ ]:
from time import process_time

Time taken by list

In [ ]:
python_list=[i for i in range(10000)]

start_time=process_time()

python_list=[i+5 for i in python_list]

end_time=process_time()

print(end_time-start_time)

0.0007685309999985179


In [ ]:
np_array=np.array([i for i in range(10000)])

start_time=process_time()

np_array+=5

end_time=process_time()

print(end_time-start_time)


0.0008396109999999624


numpy array

In [ ]:
# list
list1=[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
numpy_array=np.array([1,2,3,4,5])
print(numpy_array)
type(numpy_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
# creatind 1 dim array

a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape

(4,)

In [ ]:
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)


[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.shape

(2, 4)

In [ ]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


initial placeholder in numpy



In [ ]:
# creating a numpy array of zeros

x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# creating a numpy array of ones

y=np.ones((3,3))

print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# array of particular value

z=np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
# creating a identity matrix

a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
#creating a numpy array with random value

b=np.random.random((3,4))
print(b)

[[0.05555937 0.92588776 0.79653137 0.09751878]
 [0.24190266 0.84280993 0.52241592 0.17360194]
 [0.8847595  0.24123989 0.5460841  0.02939555]]


In [ ]:
# creating  a integer value array within a specific range

c=np.random.randint(10,100,(3,5))

print(c)

[[23 43 55 46 96]
 [99 47 67 44 48]
 [23 17 60 40 76]]


In [ ]:
# array of evenly spaced values----> specifing the number of values required

d=np.linspace(10,30,10)
print(d)

[10.         12.22222222 14.44444444 16.66666667 18.88888889 21.11111111
 23.33333333 25.55555556 27.77777778 30.        ]


In [ ]:
# array of evenly spaced values ----> specifying the step

e=np.arange(10,30,2)
print(e)

[10 12 14 16 18 20 22 24 26 28]


In [ ]:
  #convert list to a numpy array

  list2=[10,20,30,40,50]

  numpy__array=np.asarray(list2)
  print(numpy__array)
  type(numpy__array)

[10 20 30 40 50]


numpy.ndarray

Analysing a numpy array

In [ ]:
c=np.random.randint(10,90,(5,5))

print(c)

[[72 67 21 82 57]
 [14 46 75 81 85]
 [58 33 84 64 20]
 [69 54 15 23 21]
 [89 73 83 13 60]]


In [ ]:
# array dimension

print(c.shape)

(5, 5)


In [ ]:
# number of dimension

print(c.ndim)

2


In [ ]:
# number of element in an array

print(c.size)

25


In [ ]:
# checking datatype of the values in the array
print(c.dtype)


int64


Mathmatical operations on a np array

In [ ]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
print(list1+list2)       #concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)

[[7 9 6]
 [5 3 6]
 [1 0 3]]
[[10 16 15]
 [11 17 15]
 [13 13 12]]


In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[17 25 21]
 [16 20 21]
 [14 13 15]]
[[ -3  -7  -9]
 [ -6 -14  -9]
 [-12 -13  -9]]
[[ 70 144  90]
 [ 55  51  90]
 [ 13   0  36]]
[[0.7        0.5625     0.4       ]
 [0.45454545 0.17647059 0.4       ]
 [0.07692308 0.         0.25      ]]


In [49]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))

In [50]:
print(a)
print(b)

[[0 5 7]
 [8 3 1]
 [7 7 1]]
[[13 18 16]
 [14 11 18]
 [14 12 15]]


In [51]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[13 23 23]
 [22 14 19]
 [21 19 16]]
[[-13 -13  -9]
 [ -6  -8 -17]
 [ -7  -5 -14]]
[[  0  90 112]
 [112  33  18]
 [ 98  84  15]]
[[0.         0.27777778 0.4375    ]
 [0.57142857 0.27272727 0.05555556]
 [0.5        0.58333333 0.06666667]]


Array manipulation

In [52]:
array=np.random.randint(0,10,(2,3))

print(array)

print(array.shape)

[[1 1 6]
 [5 6 3]]
(2, 3)


In [53]:
# transpose

trans=np.transpose(array)
print(trans)
print(trans.shape)

[[1 5]
 [1 6]
 [6 3]]
(3, 2)


In [55]:
array=np.random.randint(0,10,(2,3))

print(array)


[[2 4 0]
 [0 9 5]]


In [56]:
trans2=array.T
print(trans2)
print(trans2.shape)

[[2 0]
 [4 9]
 [0 5]]
(3, 2)


In [57]:
# reshaping a array

a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[9 6 9]
 [4 9 3]]
(2, 3)


In [59]:
b=a.reshape(3,2)
print(b)
print(b.shape)

[[9 6]
 [9 4]
 [9 3]]
(3, 2)
